spring:
  application:
    name: backend
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://db:5432/HarmonyHomeNet_DB
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  docker:
    compose:
      file: ../compose.yaml

server:
  port: 8444
  ssl:
    enabled: true
    protocol: TLSv1.3
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bwp